name: release
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  Bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      # github_token: ${{ secrets.GITHUB_TOKEN }}
      ___X_CMD_GHACTION_X: x1
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      github_token: ${{ secrets.X_GITHUB_TOKEN }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws release || true
