name: release:man
on:
  workflow_dispatch:
  # schedule:
    # - cron: '00 7 * * *'  # 15
    # - cron: '00 10 * * *'
    # - cron: '30 10 * * *'
    # - cron: '00 14 * * *'
  

jobs:
  Bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CONCURRENCY: 10
      # ___X_CMD_GHACTION_X: x1
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      github_token: ${{ secrets.X_GITHUB_TOKEN }}
      git_user: agent-zero
      git_email: 0@x-cmd.com

      BAIDU_TOKEN: ${{ secrets.BAIDU_TOKEN }}
      BING_TOKEN: ${{ secrets.BING_TOKEN }}
      UMAMI_ENDPOINT: ${{ secrets.UMAMI_ENDPOINT }}
      BAIDU_TONGJI_EN_ID: ${{ secrets.BAIDU_TONGJI_EN_ID }}
      BAIDU_TONGJI_CN_ID: ${{ secrets.BAIDU_TONGJI_CN_ID }}
      BAIDU_TONGJI_MAN_ID: ${{ secrets.BAIDU_TONGJI_MAN_ID }}
      BAIDU_TONGJI_ZIG_ID: ${{ secrets.BAIDU_TONGJI_ZIG_ID }}
      UMAMI_EN_ID: ${{ secrets.UMAMI_EN_ID }}
      UMAMI_CN_ID: ${{ secrets.UMAMI_CN_ID }}
      UMAMI_MAN_ID: ${{ secrets.UMAMI_MAN_ID }}
      UMAMI_ZIG_ID: ${{ secrets.UMAMI_ZIG_ID }}
      X_OSS_ACCESS_KEY_ID: ${{ secrets.X_OSS_ACCESS_KEY_ID }}
      X_OSS_SECRET_ACCESS_KEY: ${{ secrets.X_OSS_SECRET_ACCESS_KEY }}
      X_ALI_ACCESS_KEY_ID: ${{ secrets.X_ALI_ACCESS_KEY_ID }}
      X_ALI_ACCESS_KEY_SECRET: ${{ secrets.X_ALI_ACCESS_KEY_SECRET }}
    steps:
      - name: main
        uses: x-cmd/action@v0
        with:
          code: x ws release-man || true
