name: release:next
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '50 3 * * *'
  #   - cron: '50 12 * * *'
  

jobs:
  Bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CONCURRENCY: 10
      ___X_CMD_GHACTION_X: x1
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      github_token: ${{ secrets.X_GITHUB_TOKEN }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
    steps:
      - name: main
        uses: x-cmd/action@v0
        with:
          code: x ws release:next || true
